const pokemons = {
    dialga:{
        name:'dialga',
        front:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/483.png',
        back:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/483.png',
        attack:{
            cut:{
                atk:20,
                pp:20
            },
            headbutt:{
                atk:30,
                pp:10
            },
            flamethrower:{
                atk:40,
                pp:3
            },
            iceBeam:{
                atk:50,
                pp:2
            }
        },
        defeated:false
    },
    mewtwo:{
        name:'mewtwo',
        front:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png',
        back:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/150.png',
        attack:{
            takeDown:{
                atk:20,
                pp:20
            },
            headbutt:{
                atk:30,
                pp:10
            },
            megaPunch:{
                atk:40,
                pp:3
            },
            thunderPunch:{
                atk:50,
                pp:2
            }
        },
        defeated:false
    },
    celebi:{
        name:'celebi',
        front:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/251.png',
        back:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/251.png',
        attack:{
            confusion:{
                atk:20,
                pp:20
            },
            psychic:{
                atk:30,
                pp:10
            },
            megaPunch:{
                atk:40,
                pp:3
            },
            solarBeam:{
                atk:50,
                pp:2
            }
        },
        defeated:false
    },
    entei:{
        name:'entei',
        front:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/244.png',
        back:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/244.png',
        attack:{
            cut:{
                atk:20,
                pp:20
            },
            bite:{
                atk:30,
                pp:10
            },
            headbutt:{
                atk:40,
                pp:3
            },
            flamethrower:{
                atk:50,
                pp:2
            }
        },
        defeated:false
    },
    palkia:{
        name:'palkia',
        front:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/484.png',
        back:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/484.png',
        attack:{
            cut:{
                atk:20,
                pp:20
            },
            headbutt:{
                atk:30,
                pp:10
            },
            surf:{
                atk:40,
                pp:3
            },
            blizzard:{
                atk:50,
            }
        },
        defeated:false
    },
    lucario:{
        name:'lucario',
        front:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/448.png',
        back:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/448.png',
        attack:{
            quickAttack:{
                atk:20,
                pp:20
            },
            psychic:{
                atk:30,
                pp:10
            },
            auraSphere:{
                atk:40,
                pp:3
            },
            earthquake:{
                atk:50,
            }
        },
        defeated:false
    },
    darkrai:{
        name:'darkrai',
        front:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/491.png',
        back:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/491.png',
        attack:{
            cut:{
                atk:20,
                pp:20
            },
            headbutt:{
                atk:30,
                pp:10
            },
            iceBeam:{
                atk:40,
                pp:3
            },
            darkPulse:{
                atk:50,
            }
        },
        defeated:false
    },
    zekrom:{
        name:'zekrom',
        front:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/644.png',
        back:'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/644.png',
        attack:{
            cut:{
                atk:20,
                pp:20
            },
            fly:{
                atk:30,
                pp:10
            },
            thunderPunch:{
                atk:40,
                pp:3
            },
            darkPulse:{
                atk:50,
            }
        },
        defeated:false
    }
}